apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: rogeriocassares/go-gitops
  newTag: 56d109444477838df53d63cd244cab2b0f6b8f39
